### ISSUE TITLE
Project doesn't compile - Cycle in dependencies between targets

### ISSUE THREAD

**Issue by odemolliens** [flitsmeister/mapbox-navigation-ios#13]
Navigation SDK version: **latest**

It's not possible to build any of the targets of the project.

```
Cycle in dependencies between targets 'Example-Objective-C' and 'MapboxCoreNavigation'; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.
Cycle path: Example-Objective-C → MapboxCoreNavigation → Example-Objective-C
```

**Comment by odemolliens** [comment]
Temporary workaround, move public headers to private:
![Screenshot 2022-08-24 at 10 34 28](https://user-images.githubusercontent.com/2726958/186370991-e9115b7b-e3d7-4d28-adb8-a22cc1707cf1.png)

**Comment by Marcelhozeman** [comment]
@odemolliens Can you try this again with the latest changes?

Otherwise try to clean the project and Reset Package Cache (File -> Packages -> Reset Package Cache)
