### ISSUE TITLE
Getting started doc not working

### ISSUE THREAD

**Issue by odemolliens** [flitsmeister/mapbox-navigation-ios#15]
It's really hard to understand how to set up the libary in a project: Multiple explanations for the same things, some commands are wrong or do not exist.

Samples don't work.

** Navigation SDK version: latest**

1. Create new project
2. Add cartfile
3. Run `carthage update --platform iOS` as explained in doc

Error:
```
Building universal frameworks with common architectures is not possible. The device and simulator slices for "MapboxMobileEvents" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead.
```

Fix:
3. Run should be `carthage update --platform iOS --use-xcframeworks`

**Comment by odemolliens** [comment]
then another missing thing:

4. add Swift package `https://github.com/maplibre/maplibre-gl-native-distribution` with version `5.12.2`

**Comment by odemolliens** [comment]
Doc said:

`Follow the rest of [Carthage’s iOS integration instructions](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos). Your application target’s Embedded Frameworks should include MapboxNavigation.framework and MapboxCoreNavigation.framework.`

Then we face that issue:
![Screenshot 2022-08-24 at 10 45 25](https://user-images.githubusercontent.com/2726958/186373550-ee6f80e7-80b0-4c6e-b3aa-f1cc54b4c8bd.png)

But in fact, you have to add more than that:
![Screenshot 2022-08-24 at 10 47 02](https://user-images.githubusercontent.com/2726958/186373726-2a258c7c-907d-43f7-a232-de39498c84ef.png)

Documention should mention that all Mapbox SDK shoud be in the Embedded Frameworks too!


5. then we should configure `"Framework Search Paths"` to `$(PROJECT_DIR)/Carthage/Build/iOS`

**Comment by odemolliens** [comment]
App crash at launch:
`*** Terminating app due to uncaught exception 'MGLMissingLocationServicesUsageDescriptionException', reason: 'To use location services this app must have a NSLocationWhenInUseUsageDescription string in its Info.plist.'`

6. then we have to add an extra key on Info.plist:
![Screenshot 2022-08-24 at 12 46 12](https://user-images.githubusercontent.com/2726958/186399774-dd265205-10be-4af8-a393-b90da4215abe.png)

**Comment by Marcelhozeman** [comment]
@odemolliens I updated the `Getting Started`, see: https://github.com/flitsmeister/flitsmeister-navigation-ios. I also tested this with the code i added to the `Sample code`. I hope this helps you further?
